// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "EQSWeightParameters.generated.h"

/**
 * 8-dimensional EQS weight parameters generated by RL policy.
 * These weights configure Environment Query System tests for tactical positioning.
 *
 * Design: Decouples strategic intent from physical navigation.
 * Range: [-1, 1] normalized, scaled to [-2, 2] for EQS application.
 */
USTRUCT(BlueprintType)
struct GAMEAI_PROJECT_API FEQSWeightParameters
{
	GENERATED_BODY()

	// Distance to enemy objective (enemy base/occupied area)
	// High (+): Assault, Low (-): Retreat
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float EnemyObjectiveProximity = 0.0f;

	// Distance to friendly objective (ally base)
	// High (+): Defend, Low (-): Scout
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float AllyObjectiveProximity = 0.0f;

	// Cover density (trace to surrounding objects)
	// High (+): Retreat, Defend, Moderate: Assault
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float CoverDensity = 0.0f;

	// Line of sight to enemies
	// High (+): Assault, Scout, Low (-): Retreat
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float EnemyVisibility = 0.0f;

	// Distance to friendly agents
	// High (+): Support, Low (-): Scout
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float AllyProximity = 0.0f;

	// Optimal weapon range maintenance
	// High (+): Assault, Defend (optimal 50m)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float CombatRange = 0.0f;

	// Distance to health packs/ammo crates
	// High (+): Retreat, Support
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float PickupProximity = 0.0f;

	// Z-axis height advantage
	// High (+): Scout, Defend (high ground bonus)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "EQS Weights")
	float HeightAdvantage = 0.0f;

	FEQSWeightParameters()
		: EnemyObjectiveProximity(0.0f)
		, AllyObjectiveProximity(0.0f)
		, CoverDensity(0.0f)
		, EnemyVisibility(0.0f)
		, AllyProximity(0.0f)
		, CombatRange(0.0f)
		, PickupProximity(0.0f)
		, HeightAdvantage(0.0f)
	{}

	/**
	 * Scale from RL output range [-1, 1] to EQS range [-2, 2]
	 */
	void ScaleForEQS()
	{
		EnemyObjectiveProximity = FMath::Clamp(EnemyObjectiveProximity, -1.0f, 1.0f) * 2.0f;
		AllyObjectiveProximity = FMath::Clamp(AllyObjectiveProximity, -1.0f, 1.0f) * 2.0f;
		CoverDensity = FMath::Clamp(CoverDensity, -1.0f, 1.0f) * 2.0f;
		EnemyVisibility = FMath::Clamp(EnemyVisibility, -1.0f, 1.0f) * 2.0f;
		AllyProximity = FMath::Clamp(AllyProximity, -1.0f, 1.0f) * 2.0f;
		CombatRange = FMath::Clamp(CombatRange, -1.0f, 1.0f) * 2.0f;
		PickupProximity = FMath::Clamp(PickupProximity, -1.0f, 1.0f) * 2.0f;
		HeightAdvantage = FMath::Clamp(HeightAdvantage, -1.0f, 1.0f) * 2.0f;
	}

	/**
	 * Serialize to array for logging/debugging
	 */
	TArray<float> ToArray() const
	{
		return {
			EnemyObjectiveProximity,
			AllyObjectiveProximity,
			CoverDensity,
			EnemyVisibility,
			AllyProximity,
			CombatRange,
			PickupProximity,
			HeightAdvantage
		};
	}

	FString ToString() const
	{
		return FString::Printf(TEXT("EnemyObj:%.2f, AllyObj:%.2f, Cover:%.2f, EnemyVis:%.2f, AllyProx:%.2f, Range:%.2f, Pickup:%.2f, Height:%.2f"),
			EnemyObjectiveProximity, AllyObjectiveProximity, CoverDensity, EnemyVisibility,
			AllyProximity, CombatRange, PickupProximity, HeightAdvantage);
	}
};
