;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Game/Tables/DT_GameplayTagTable.DT_GameplayTagTable
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Ability.Attack.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Damaged",DevComment="")
+GameplayTagList=(Tag="StateTree.Follower.Died",DevComment="Sent when follower agent dies")
+GameplayTagList=(Tag="StateTree.Follower.MissionReceived",DevComment="Sent when follower receives a new mission from team leader")
+GameplayTagList=(Tag="StateTree.Follower.Respawned",DevComment="Sent when follower agent respawns after death")

