// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Types/MocTypes.h"
#include "RL/Observation/MocObservation.h"
#include "MocTransitionLogger.generated.h"

class AMocCharacter;
class UMocRewardCalculator;

/**
 * Single transition record for training
 * Format: (State, Option, Action, Reward, NextState, Done)
 */
USTRUCT(BlueprintType)
struct FMocTransition
{
	GENERATED_BODY()

	/** Current state observation (52-dim) */
	UPROPERTY(BlueprintReadOnly)
	FObservation State;

	/** Active strategy option */
	UPROPERTY(BlueprintReadOnly)
	EStrategyType OptionType = EStrategyType::Assault;

	/** Target position assigned by MCTS */
	UPROPERTY(BlueprintReadOnly)
	FVector TargetPosition = FVector::ZeroVector;

	/** Option duration (expected) */
	UPROPERTY(BlueprintReadOnly)
	float OptionDuration = 0.0f;

	/** EQS weights generated by policy (8-dim) */
	UPROPERTY(BlueprintReadOnly)
	TArray<float> EQSWeights;

	/** Reward received */
	UPROPERTY(BlueprintReadOnly)
	float Reward = 0.0f;

	/** Next state observation (52-dim) */
	UPROPERTY(BlueprintReadOnly)
	FObservation NextState;

	/** Episode terminated */
	UPROPERTY(BlueprintReadOnly)
	bool bDone = false;

	/** Timestamp */
	UPROPERTY(BlueprintReadOnly)
	float Timestamp = 0.0f;

	/** Agent ID */
	UPROPERTY(BlueprintReadOnly)
	int32 AgentID = -1;

	/** Team ID */
	UPROPERTY(BlueprintReadOnly)
	int32 TeamID = -1;

	/** Episode ID */
	UPROPERTY(BlueprintReadOnly)
	int32 EpisodeID = -1;

	FMocTransition() = default;
};

/**
 * Transition logger for MOC training pipeline.
 *
 * Responsibilities:
 * - Collect (S, O, A, R, S', Done) transitions
 * - Export to CSV for Python training
 * - Support batched writes (reduce I/O overhead)
 * - Provide replay buffer access for on-policy learning
 *
 * Output Format:
 * CSV with columns: EpisodeID, AgentID, TeamID, Timestamp, State[52], OptionType,
 *                   TargetPos[3], Duration, EQSWeights[8], Reward, NextState[52], Done
 *
 * Target: 100,000 transitions for Phase 1 training
 */
UCLASS(ClassGroup=(MOC), meta=(BlueprintSpawnableComponent))
class GAMEAI_PROJECT_API UMocTransitionLogger : public UActorComponent
{
	GENERATED_BODY()

public:
	UMocTransitionLogger();

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

public:
	/**
	 * Log single transition
	 */
	UFUNCTION(BlueprintCallable, Category = "MOC|Logging")
	void LogTransition(
		const FObservation& State,
		EStrategyType OptionType,
		const FVector& TargetPosition,
		float OptionDuration,
		const TArray<float>& EQSWeights,
		float Reward,
		const FObservation& NextState,
		bool bDone
	);

	/**
	 * Start new episode
	 */
	UFUNCTION(BlueprintCallable, Category = "MOC|Logging")
	void StartEpisode();

	/**
	 * End current episode and flush buffer
	 */
	UFUNCTION(BlueprintCallable, Category = "MOC|Logging")
	void EndEpisode(bool bTeamWon);

	/**
	 * Flush transition buffer to disk (CSV)
	 */
	UFUNCTION(BlueprintCallable, Category = "MOC|Logging")
	void FlushToDisk();

	/**
	 * Get transition count
	 */
	UFUNCTION(BlueprintPure, Category = "MOC|Logging")
	int32 GetTransitionCount() const { return TotalTransitions; }

	/**
	 * Get current episode ID
	 */
	UFUNCTION(BlueprintPure, Category = "MOC|Logging")
	int32 GetEpisodeID() const { return CurrentEpisodeID; }

	/**
	 * Set output directory for CSV files
	 */
	UFUNCTION(BlueprintCallable, Category = "MOC|Logging")
	void SetOutputDirectory(const FString& Directory) { OutputDirectory = Directory; }

	/**
	 * Enable/disable logging
	 */
	UFUNCTION(BlueprintCallable, Category = "MOC|Logging")
	void SetLoggingEnabled(bool bEnabled) { bLoggingEnabled = bEnabled; }

protected:
	/** Transition buffer (flushed at episode end or every 1000 transitions) */
	UPROPERTY()
	TArray<FMocTransition> TransitionBuffer;

	/** Output directory for CSV files */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Logging")
	FString OutputDirectory = TEXT("Saved/MOC_Training");

	/** Current episode ID */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Logging")
	int32 CurrentEpisodeID = 0;

	/** Total transitions logged */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Logging")
	int32 TotalTransitions = 0;

	/** Current episode transition count */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Logging")
	int32 EpisodeTransitions = 0;

	/** Enable logging */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Logging")
	bool bLoggingEnabled = true;

	/** Batch size for disk writes (reduce I/O overhead) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Logging")
	int32 FlushBatchSize = 1000;

	/** Owner character */
	UPROPERTY()
	AMocCharacter* OwnerCharacter;

private:
	/**
	 * Write transitions to CSV file
	 */
	void WriteToCSV(const TArray<FMocTransition>& Transitions);

	/**
	 * Serialize observation to string
	 */
	FString SerializeObservation(const FObservation& Obs) const;

	/**
	 * Get CSV file path
	 */
	FString GetCSVFilePath() const;

	/** File handle for batched writing */
	IFileHandle* FileHandle = nullptr;
};
